### ISSUE TITLE
dt1 viewer: crashes when opening certain files

### ISSUE THREAD

**Issue by ianling** [OpenDiablo2/HellSpawner#141]
To reproduce:

- Create a project, add d2_data.mpq
- Using the MPQ Explorer, open d2_data.mpq/data/global/tiles/ACT1/TOWN/trees.dt1
- HellSpawner crashes

Stack trace:

```
panic: reflect: slice index out of range

goroutine 1 [running, locked to thread]:
reflect.Value.Index(0x8644a0, 0xc0002b9440, 0x97, 0x0, 0x8644a0, 0x7fef00000000, 0x1605cd8)
        /snap/go/6745/src/reflect/value.go:962 +0x1f2
github.com/go-gl/gl/v3.2-core/gl.Ptr(0x8644a0, 0xc0002b9440, 0x0)
        /home/iling/go/pkg/mod/github.com/go-gl/gl@v0.0.0-20190320180904-bf2b1f2f34d7/v3.2-core/gl/conversions.go:44 +0x126
github.com/AllenDang/giu/imgui.(*OpenGL3).createImageTexture(0xc000062410, 0xc0011c4f00, 0x0, 0xc000a8ef40, 0xc001605e3c)
        /home/iling/go/pkg/mod/github.com/!allen!dang/giu@v0.5.1-0.20210103063223-76b922d44612/imgui/RendererOpenGL3.go:447 +0x165
github.com/AllenDang/giu/imgui.(*OpenGL3).LoadImage(0xc000062410, 0xc0011c4f00, 0xc001605e50, 0xc000af2c60, 0xc000000208)
        /home/iling/go/pkg/mod/github.com/!allen!dang/giu@v0.5.1-0.20210103063223-76b922d44612/imgui/RendererOpenGL3.go:424 +0x35
github.com/AllenDang/giu.NewTextureFromRgba.func1(0xc0000b68a0, 0xc001605df0)
        /home/iling/go/pkg/mod/github.com/!allen!dang/giu@v0.5.1-0.20210103063223-76b922d44612/Texture.go:27 +0x42
github.com/faiface/mainthread.CallVal.func1()
        /home/iling/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:84 +0x32
github.com/faiface/mainthread.Run(0xc00000e100)
        /home/iling/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:44 +0xbd
github.com/AllenDang/giu.(*MasterWindow).Run(0xc00008e000, 0xc000290010)
        /home/iling/go/pkg/mod/github.com/!allen!dang/giu@v0.5.1-0.20210103063223-76b922d44612/MasterWindow.go:238 +0x65
github.com/OpenDiablo2/HellSpawner/hsapp.(*App).Run(0xc00015a120)
        /home/iling/github/HellSpawner/hsapp/app.go:82 +0x179
main.main()
        /home/iling/github/HellSpawner/main.go:16 +0xa5
```

**Comment by gucio321** [comment]
crashes here:
https://github.com/OpenDiablo2/HellSpawner/blob/358ae8260a2a94f7c941aad6cf35a6d70e82fa64/hswidget/dt1viewer.go#L197
